Operations Status Search API Endpoint
magento/bulk-api-ce pull request #12
Opened 2018-04-12 18:33 UTC by anvasiliev

Allow to receive all bulk operations by search criteria. 

### Description
https://github.com/magento-engcom/bulk-api/wiki/Operations-Status-Search-API-Endpoint

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-05-09 19:47 UTC, vrann commented
- [ ] documentation needed

2018-05-17 15:59 UTC, nuzil commented
PR is ready

2018-05-22 19:47 UTC, keharper commented
@nuzil @vrann Place documentation files under here:

https://github.com/magento/devdocs/tree/develop/guides/v2.3/rest

If you have multiple `.md` files, create a subdirectory named `bulk-api` and place the files in there.

2018-05-22 20:53 UTC, paliarush requested changes

2018-05-22 20:53 UTC, paliarush commented on app/code/Magento/AsynchronousOperations/Api/Data/OperationSearchResultsInterface.php
> +interface OperationSearchResultsInterface extends \Magento\Framework\Api\SearchResultsInterface
Please add description to all new classes/interfaces

2018-05-22 20:53 UTC, paliarush commented on app/code/Magento/AsynchronousOperations/Api/Data/OperationSearchResultsInterface.php
> +     * Get attributes list.
`attributes list` => `operations list` ?

2018-05-22 20:53 UTC, paliarush commented on app/code/Magento/AsynchronousOperations/Model/OperationRepository.php
> +        $this->collectionProcessor = $collectionProcessor ? : ObjectManager::getInstance()
This is a new class, what is the reason to use object manager (it is normally used for backward compatibility)?

2018-05-22 20:53 UTC, paliarush commented on app/code/Magento/AsynchronousOperations/Model/OperationRepository.php
> +        CollectionProcessorInterface $collectionProcessor = null,
This argument should not be optional.

2018-05-22 20:53 UTC, paliarush commented on app/code/Magento/AsynchronousOperations/Model/OperationRepository.php
> +            $extensionAttributes->setStartTime('dsadsa');
What does 'dsadsa' mean?

2018-05-22 20:53 UTC, paliarush commented on lib/internal/Magento/Framework/Bulk/OperationInterface.php
> +interface OperationInterface extends \Magento\Framework\Api\ExtensibleDataInterface
In theory, `OperationInterface` must have `getExtensionAttributes` and `setExtensionAttributes` declared. 

What is the need to move inheritance from `ExtensibleDataInterface` up to this interface?

2018-06-27 09:59 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/bulk-api-ce?pullRequest=12) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/bulk-api-ce?pullRequest=12) before we can accept your contribution.<br/>

2018-06-27 10:36 UTC, anvasiliev commented on lib/internal/Magento/Framework/Bulk/OperationInterface.php
> +interface OperationInterface extends \Magento\Framework\Api\ExtensibleDataInterface
In other case I get logic exception from Magento\Framework\Api\ExtensionAttributesFactory::getExtensibleInterfaceName($extensibleClassName) because Magento\AsynchronousOperations\Api\Data\OperationInterface and parent interfaces doesn't extend \Magento\Framework\Api\ExtensibleDataInterface

2018-06-27 21:07 UTC, merged