Change Webapi extension to use Inject Pool logic
magento/bulk-api-ce pull request #20
Opened 2018-05-15 13:59 UTC by nuzil

We extended Magento/Webapi extension. This allowed us to use Request Processors Pool and avoid of using if/else statements in \Magento\Webapi\Controller\Rest.php

2018-05-22 22:23 UTC, paliarush requested changes
I assume there were no conflicts during backporting, if there were any, please highlight them.

2018-05-22 22:23 UTC, paliarush commented on app/code/Magento/Webapi/Controller/Rest.php
> +        RequestProcessorPool $requestProcessorPool
Since the changes are targeted for patch release, all new dependencies must be introduced in a backwards compatible manner (using object manager and marking the argument as optional). 
Sequence of arguments should not be modified.

In this specific case there is no high risk that someone inherited from this class, but we must do all we can to avoid backward incompatible changes.

2018-05-22 22:23 UTC, paliarush commented on app/code/Magento/Webapi/Controller/Rest.php
> -    protected function processSchemaRequest()
Protected methods cannot be removed because of backward compatibility reasons. Please mark them as deprecated.

2018-05-28 12:35 UTC, nuzil commented on app/code/Magento/Webapi/Controller/Rest.php
> -    protected function processSchemaRequest()
@paliarush 
what is a correct version here? 
 @deprecated 100.1.0 ?

2018-05-28 12:48 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/bulk-api-ce?pullRequest=20) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/bulk-api-ce?pullRequest=20) before we can accept your contribution.<br/>

2018-05-28 12:48 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/bulk-api-ce?pullRequest=20) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/bulk-api-ce?pullRequest=20) before we can accept your contribution.<br/>

2018-06-05 16:16 UTC, vrann commented
@nuzil please fix static tests

2018-06-27 19:07 UTC, merged