Custom route for bulk api
magento/bulk-api-ce pull request #21
Opened 2018-05-18 21:04 UTC by nuzil

Customisable rest route for Async Bulk API so that generated path can be overwritten 
Added XML file which declares the bulk API endpoint.

2018-05-18 21:04 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/bulk-api-ce?pullRequest=21) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/bulk-api-ce?pullRequest=21) before we can accept your contribution.<br/>

2018-05-18 21:04 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/bulk-api-ce?pullRequest=21) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/bulk-api-ce?pullRequest=21) before we can accept your contribution.<br/>

2018-05-19 11:23 UTC, vrann requested changes
There is already file webapi_async.xml, it would be better to reuse it, instead of adding a new one.
Another option is to add some attribute, i,e, "bulk" to the webapi.xml

@apaliarush what do you think?

2018-05-19 11:24 UTC, vrann commented on app/code/Magento/WebapiAsync/Model/RouteCustomizationConfig.php
> +        if (null === $this->routeCustomizations) {
config files are cached automatically, after structure is converted to array in Converter, there is no need to cache it again.

2018-05-22 23:07 UTC, paliarush commented on app/code/Magento/WebapiAsync/Model/RouteCustomizationConfig.php
> +        if (null === $this->routeCustomizations) {
@vrann agree, we should re-use existing config. Also would be nice to allow override of this config parameter via deployment config (etc/env.php). See how it is done in message queue via custom config reader for deployment config.

2018-05-22 23:15 UTC, paliarush commented
Does it make sense to introduce such feature for any web API routes?
If so, then it could be implemented in Webapi module directly without plugins.

2018-05-23 17:06 UTC, misha-kotov commented
Yes, I think this functionality would provide value for all web API routes, not just Async/Bulk.

2018-05-26 14:21 UTC, nuzil commented
@Neos2007 can you please check tests + implement this feature for ALL routes as described before

2018-06-06 17:56 UTC, Neos2007 commented
So custom routes logic must be implemented in Webapi module?
If that, for custom routes configuration a propose to add "custom_route" along with "route" nodes.
Will looks like: 
`<custom_route requested_path="asyncCustomers" endpoint="async/V1/customers"/> 
<custom_route requested_path="asyncBulkCmsPages" endpoint="async/bulk/V1/cmsPage" />`

2018-06-07 15:31 UTC, vrann commented
@Neos2007 we discussed the concerns with @paliarush, so couple comments:
- we don't need to be able to rewrite it in env.php
- we don't need separate file to define overrides. Instead we propose to use `webapi_async.xml`
- the format of the new node:
```
<route url="" method="" alias="" />
```
All params should be required. Param `method` should allow only POST PUT DELETE GET
Nodes should be merged based on combination of `url` and `method` (composite identifier)

2018-06-14 20:44 UTC, Neos2007 commented
Modified logic of adding custom routes for asynchronous rest api.
Needed configuration for custom routes can be added to webapi_async.xml file as nodes inside root node.
Example:
`<route url="async/V1/products" method="POST" alias="asyncProducts" />`

2018-06-19 17:22 UTC, paliarush requested changes
1. Would be nice to declare some real aliases for existing endpoints, these would serve as good examples (in addition to tests)
2. We should add at least one web API functional test for the implemented functionality

2018-06-19 17:22 UTC, paliarush commented on app/code/Magento/WebapiAsync/Model/ServiceConfig/Converter.php
> +        \Magento\Webapi\Model\Rest\Config::HTTP_METHOD_GET,
We should also allow `PATCH` for partial updates. It is stated in our web API technical vision https://devdocs.magento.com/guides/v2.2/coding-standards/technical-vision/webapi.html.

 Please add `PATCH` support for synchronous web APIs as well if not implemented yet and if time permits.

2018-06-19 17:22 UTC, paliarush commented on app/code/Magento/WebapiAsync/Model/ServiceConfig/Converter.php
> +     * Convert and merge "route" nodes, which represent route customizations
Please correct formatting. 
Also, all new methods and classes must be documented across the review.

2018-06-19 17:22 UTC, paliarush commented on app/code/Magento/WebapiAsync/Plugin/ControllerRest.php
> +     * Check is current rest api route path in route customization config.
The description does not sound right. Please use something like "Apply route customization.", or get current version reviewed with English native speaker.

2018-06-26 12:27 UTC, nuzil commented
If I understand correctly Tests are failed not because of PR

2018-06-26 19:46 UTC, vrann approved these changes

2018-06-27 00:29 UTC, merged