The user passed for async api referenced correct WebAPI user
magento/bulk-api-ce pull request #22
Opened 2018-05-18 21:12 UTC by nuzil

https://app.zenhub.com/workspace/o/magento/bulk-api-ce/issues/14

Drop foreign key referencing admin_user table from bulk operations. Pass the Web API user id taken from the context object to MassScheduler

2018-05-18 21:12 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/bulk-api-ce?pullRequest=22) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/bulk-api-ce?pullRequest=22) before we can accept your contribution.<br/>

2018-05-18 21:12 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/bulk-api-ce?pullRequest=22) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/bulk-api-ce?pullRequest=22) before we can accept your contribution.<br/>

2018-05-19 11:18 UTC, vrann commented
@nuzil @anvasiliev can you please fix travis and sign CLA

2018-05-23 15:12 UTC, paliarush requested changes

2018-05-23 15:12 UTC, paliarush commented on app/code/Magento/AsynchronousOperations/Model/MassSchedule.php
> +            $userId = $this->userContext->getUserId();
User ID is not unique identifier and should be used in conjunction with user type.

There could be integration, admin and customer with the same ID. I believe bulk operation could at least be scheduled by the admin or integration.

2018-05-29 07:02 UTC, munkhulzii commented on app/code/Magento/AsynchronousOperations/Model/MassSchedule.php
> +            $userId = $this->userContext->getUserId();
you are right the user ID is not unique. 

@anvasiliev @nuzil How do you think if we save the user type?

2018-05-29 08:10 UTC, nuzil commented on app/code/Magento/AsynchronousOperations/Model/MassSchedule.php
> +            $userId = $this->userContext->getUserId();
Hi @paliarush , @vrann 
We though about 2 possible solutions, maybe we have to discuss it separately: 
1) We will add prefixes to users, like "admin_ID, customer_ID" .....
2) We will add new column to this table with user_type.

What do you think?

2018-06-15 16:35 UTC, vrann submitted a review, later dismissed

2018-06-15 16:35 UTC, vrann commented on app/code/Magento/AsynchronousOperations/Model/MassSchedule.php
> +            $userId = $this->userContext->getUserId();
@munkhulzii @nuzil it would be a cleaner solution if we add another column, with the default value set to the admin. Otherwise it will be backward incompatible with the rest of the system

2018-08-31 18:13 UTC, paliarush commented on app/code/Magento/AsynchronousOperations/Api/Data/BulkSummaryInterface.php
> +     * @param int $operationCount
Looks like copy-paste

2018-08-31 18:16 UTC, paliarush commented on app/code/Magento/AsynchronousOperations/Test/Unit/Model/BulkManagementTest.php
> +        $userType = 2;
User types are defined in `\Magento\Authorization\Model\UserContextInterface` as constants. Please use one of those constants to make code cleaner.

2018-09-13 14:22 UTC, vkublytskyi requested changes

2018-09-13 14:22 UTC, vkublytskyi commented on app/code/Magento/AsynchronousOperations/Model/BulkManagement.php
> +        UserContextInterface $userContext,
This constructor exists in Magento Commerce 2.2 so new parameters should be added corresponding to backward compatibility policies (at the end as optional)

2018-09-13 14:22 UTC, vkublytskyi commented on app/code/Magento/AsynchronousOperations/Model/MassSchedule.php
> +        UserContextInterface $userContext
This constructor exists in Magento Commerce 2.2 so new parameters should be added corresponding to backward compatibility policies (as optional)

2018-09-14 13:58 UTC, vkublytskyi requested changes
Before merge following issues should be resolved:
- The class MassSchedule has a coupling between objects value of 13. Consider to reduce the number of dependencies under 13.
- During upgrade foreign key `MAGENTO_BULK_USER_ID_ADMIN_USER_USER_ID` is not dropped for Magento Commerce installation.

2018-10-05 21:12 UTC, rganin commented on app/code/Magento/AsynchronousOperations/etc/db_schema_whitelist.json
> -    "magento_bulk": {
Please keep 4 spaces intendation for whitelists, changes are very hard to read.

2018-10-05 21:12 UTC, rganin commented on lib/internal/Magento/Framework/Setup/Declaration/Schema/Diff/TableDiff.php
> +                // declared constraint. If constraint is not declared we should clean up index created for it.
What is the purpose of this change?
It causes a case when autogenerated index will be implicitly removed from declaration so removing FK with preserving index for performance purposes won't work.

2018-10-05 21:12 UTC, rganin commented on lib/internal/Magento/Framework/Setup/Declaration/Schema/Diff/TableDiff.php
> +                // declared constraint. If constraint is not declared we should clean up index created for it.
If you need to remove index use declaration with 'disable="1"' attribute.

2018-10-10 10:15 UTC, vkublytskyi approved these changes

2018-10-10 10:18 UTC, merged