Add support for topic schema defined as ServiceName:methodName
magento/bulk-api-ce pull request #23
Opened 2018-05-22 18:19 UTC by anvasiliev

PR add support for topic type schema defined as ServiceName:methodName by force changing sync type to async, but only if topic name starts with \Magento\AsynchronousOperations\Model\ConfigInterface::TOPIC_PREFIX, e.g. async.some.topic

2018-05-22 18:19 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/signed)](https://cla.dev.magento.com/magento/bulk-api-ce?pullRequest=23) <br/>All committers have signed the CLA.

2018-05-22 18:19 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/bulk-api-ce?pullRequest=23) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/bulk-api-ce?pullRequest=23) before we can accept your contribution.<br/><hr/>**Vasiliev.A** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2018-05-23 15:24 UTC, paliarush reviewed
Please explain the purpose of the task, not clear from the PR description.

2018-05-23 15:24 UTC, paliarush commented on app/code/Magento/WebapiAsync/Plugin/Communication/Config/CompositeReader.php
> +class CompositeReader
Please add class documentation

2018-05-23 15:24 UTC, paliarush commented on app/code/Magento/WebapiAsync/Plugin/Communication/Config/CompositeReader.php
> +     * Topics with type schema is always are sync
Description does not sound right, please correct

2018-06-27 21:03 UTC, vrann commented
@anvasiliev the problem described in bug was more related to the fact that in `\Magento\Framework\MessageQueue\Consumer` the topic type definition `CommunicationConfig::TOPIC_REQUEST_TYPE_METHOD` is supported: https://github.com/magento/bulk-api-ce/blob/2.3-develop/lib/internal/Magento/Framework/MessageQueue/Consumer.php#L135

While it is not supported here https://github.com/magento/bulk-api-ce/blob/2.3-develop/app/code/Magento/AsynchronousOperations/Model/MassConsumer.php#L109

Also, I don't think we need a plugin to convert topic to asynchronous, because all topics generated with `async` prefix will be defined using request type TOPIC_REQUEST_TYPE_CLASS.

But in case if somebody uses MassConsumer to process some other queue defined manually throughthe communication.xml, the support of TOPIC_REQUEST_TYPE_METHOD will be important

2018-09-04 14:45 UTC, paliarush commented on lib/internal/Magento/Framework/Communication/Config/Reader/XmlReader/Converter.php
> +                    Config::TOPIC_IS_SYNCHRONOUS => $isSynchronous ?? false,
How can this request be synchronous?

2018-09-04 14:55 UTC, paliarush commented on lib/internal/Magento/Framework/Communication/Config/ReflectionGenerator.php
> +                ? : [self::DEFAULT_HANDLER => $methodMetadata[Config::SCHEMA_METHOD_HANDLER]]
I believe this is accidental change.

2018-09-04 14:57 UTC, paliarush commented on lib/internal/Magento/Framework/Communication/Config/ReflectionGenerator.php
>       * Perform the following conversion:
There should be an empty line between short and long descriptions.

2018-09-04 15:06 UTC, paliarush commented on lib/internal/Magento/Framework/Communication/Config/ReflectionGenerator.php
> +        $isSynchronous = null
Is this already used anywhere?

2018-09-04 15:07 UTC, paliarush requested changes
Please address comments above and cover with tests.

2018-09-12 09:29 UTC, anvasiliev commented on lib/internal/Magento/Framework/Communication/Config/Reader/XmlReader/Converter.php
> +                    Config::TOPIC_IS_SYNCHRONOUS => $isSynchronous ?? false,
Request will be synchronous in next etc/communication.xml configs:
1. Topic attributes "request" and "response" are both defined, attribute "is_synchronous" not defined or "true".
`<topic name="example.sync.topic" request="Magento\Example\Api\Data\EntityInterface" response="Magento\Example\Api\Data\EntityInterface">
        <handler name="handler" type="Magento\Example\Api\EntityRepositoryInterface" method="save"/>
    </topic>`
2. Topic attribute "schema" defined and attribute "is_synchronous" not defined or "true"
`<topic name="example.sync.topic" schema="Magento\Example\Api\EntityRepositoryInterface::save">
        <handler name="handler" type="Magento\Example\Api\EntityRepositoryInterface" method="save"/>
</topic>`

2018-09-12 10:17 UTC, anvasiliev commented on lib/internal/Magento/Framework/Communication/Config/ReflectionGenerator.php
> +        $isSynchronous = null
was not used anywhere. Fixed in last commit

2018-09-17 11:28 UTC, vkublytskyi requested changes
Please review comments and failed integration tests

2018-09-17 11:28 UTC, vkublytskyi commented on lib/internal/Magento/Framework/Communication/Config/Reader/XmlReader/Converter.php
> +    protected function extractTopicIsSynchronous($topicNode)
As this is new method it should be `private`

2018-09-17 11:28 UTC, vkublytskyi commented on lib/internal/Magento/Framework/Communication/Config/Reader/XmlReader/Converter.php
> +            return null;
Please avoid methods with multiple return types. If some value should be applied by default this is the best place to define it. With this PHP return type declaration should be used for new code

```php
private function extractTopicIsSynchronous($topicNode): bool
```

2018-09-17 11:28 UTC, vkublytskyi commented on lib/internal/Magento/Framework/Communication/Config/Reader/XmlReader/Converter.php
> +        $isSynchronous = filter_var($value, FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
If XML file contains inappropriate value it should lead to an exception. Ideally, such case should be avoided by providing corresponding restrictions in XSD file.

2018-09-17 11:28 UTC, vkublytskyi commented on lib/internal/Magento/Framework/Communication/Config/Reader/XmlReader/Converter.php
> +                    Config::TOPIC_IS_SYNCHRONOUS => $isSynchronous ?? false,
@anvasiliev, seems there is a bug in the implementation. If `is_synchronous` is missed then `extractTopicIsSynchronous` return `null` which is treated as false. To avoid such issue better always return boolean from `extractTopicIsSynchronous`.

Also, I suppose, @paliarush question was about what is the reason to support asynchrony for topics that only send data and don't expect any response. Looks like for the last `elseif ($requestSchema)` we should always have `Config::TOPIC_IS_SYNCHRONOUS => false` regardless attribute value.

2018-09-19 12:15 UTC, vkublytskyi commented
Code looks good. PR will be merged if manual QA doesn't discover bugs.

2018-10-25 23:56 UTC, paliarush approved these changes

2019-01-15 16:42 UTC, vkublytskyi approved these changes

2019-01-16 08:46 UTC, nuzil approved these changes

2019-01-27 20:51 UTC, merged